name: .NET Release

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: '创建Release并上传产物'
        required: true
        default: false
        type: boolean
      version:
        description: '版本号'
        required: false
        default: '3.7.0'
      release_notes:
        description: '更新说明'
        required: false
        default: 'DanhengServer3.7.0，安卓代理地址https://github.com/Xuoos/AnimeGamesProxy/releases/latest'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Publish win-x64
      run: dotnet publish Program/Program.csproj -o Release/win-x64 -r win-x64 --self-contained true --framework net9.0 -p:PublishSingleFile=true -p:DebugType=none

    - name: Publish linux-x64
      run: dotnet publish Program/Program.csproj -o Release/linux-x64 -r linux-x64 --self-contained true --framework net9.0 -p:PublishSingleFile=true -p:DebugType=none

    - name: Publish linux-arm64
      run: dotnet publish Program/Program.csproj -o Release/linux-arm64 -r linux-arm64 --self-contained true --framework net9.0 -p:PublishSingleFile=true -p:DebugType=none

    - name: Upload win-x64 Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DanhengServer-win-64
        path: Release/win-x64

    - name: Upload linux-x64 Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DanhengServer-linux-x64
        path: Release/linux-x64

    - name: Upload linux-arm64 Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: DanhengServer-linux-arm64
        path: Release/linux-arm64

    - name: Zip artifacts for release
      if: github.event.inputs.create_release == 'true'
      run: |
        mkdir -p z
        cd Release
        zip -r ../z/DanhengServer-win-x64.zip win-x64/
        zip -r ../z/DanhengServer-linux-x64.zip linux-x64/
        zip -r ../z/DanhengServer-linux-arm64.zip linux-arm64/
        cd ..

    - name: Create GitHub Release
      if: github.event.inputs.create_release == 'true'
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ inputs.version }}
        tag_name: v${{ inputs.version }}
        body: ${{ inputs.release_notes }}
        token: ${{ secrets.GITHUB_TOKEN }}
        files: |
          z/DanhengServer-win-x64.zip
          z/DanhengServer-linux-x64.zip
          z/DanhengServer-linux-arm64.zip
